[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx.workspace = true
thiserror.workspace = true
tracing.workspace = true
chrono.workspace = true
serde.workspace = true
